# Site settings
title: Academic website of Bhav Ashok
email: bhav@cmu.edu
description: > # this means to ignore newlines until "baseurl:"
    Academic portfolio website of Anubhav Ashok
baseurl: "/academic" # the subpath of your site, e.g. /blog/
url: "https://anubhavashok.github.io/" # the base hostname & protocol for your site
twitter_username: bhavashok 
github_username: anubhavashok 

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: ""
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
